### ISSUE TITLE
Update Spark to 2.0

### ISSUE THREAD

**Issue by Georgehe4** [Georgehe4/mango#5]
Changes tracked at https://github.com/Georgehe4/mango/tree/scala2.11_update

**Comment by Georgehe4** [comment]
Need to upgrade to scala 2.11 - blocked by parquet version (only works with scala 2.10)

Resolved by downgrading parquet to scala 2.10 manually

**Comment by Georgehe4** [comment]
java.lang.NoSuchMethodError: org.apache.spark.SparkContext.emptyRDD(Lscala/reflect/ClassTag;)Lorg/apache/spark/rdd/EmptyRDD;
    at org.bdgenomics.mango.models.LazyMaterialization.put(LazyMaterialization.scala:136)
    at org.bdgenomics.mango.models.LazyMaterialization.getJson(LazyMaterialization.scala:90)
    at org.bdgenomics.mango.cli.VizServlet$$anonfun$11.apply(VizReads.scala:314)
    at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$liftAction(ScalatraBase.scala:285)
    at org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:279)
    at org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:279)
    at org.scalatra.ScalatraBase$class.withRouteMultiParams(ScalatraBase.scala:356)
    at org.bdgenomics.mango.cli.VizServlet.withRouteMultiParams(VizReads.scala:206)
    at org.scalatra.ScalatraBase$class.invoke(ScalatraBase.scala:278)
    at org.bdgenomics.mango.cli.VizServlet.invoke(VizReads.scala:206)
    at org.scalatra.ScalatraBase$$anonfun$runRoutes$1$$anonfun$apply$8.apply(ScalatraBase.scala:253)
    at org.scalatra.ScalatraBase$$anonfun$runRoutes$1$$anonfun$apply$8.apply(ScalatraBase.scala:251)
    at scala.Option.flatMap(Option.scala:171)
    at org.scalatra.ScalatraBase$$anonfun$runRoutes$1.apply(ScalatraBase.scala:251)
    at org.scalatra.ScalatraBase$$anonfun$runRoutes$1.apply(ScalatraBase.scala:250)
    at scala.collection.immutable.Stream.flatMap(Stream.scala:493)
    at org.scalatra.ScalatraBase$class.runRoutes(ScalatraBase.scala:250)
    at org.bdgenomics.mango.cli.VizServlet.runRoutes(VizReads.scala:206)
    at org.scalatra.ScalatraBase$class.runActions$1(ScalatraBase.scala:175)
    at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply$mcV$sp(ScalatraBase.scala:187)
    at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:187)
    at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:187)
    at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$cradleHalt(ScalatraBase.scala:205)
    at org.scalatra.ScalatraBase$class.executeRoutes(ScalatraBase.scala:187)
    at org.bdgenomics.mango.cli.VizServlet.executeRoutes(VizReads.scala:206)
    at org.scalatra.ScalatraBase$$anonfun$handle$1.apply$mcV$sp(ScalatraBase.scala:126)
    at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:126)
    at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:126)
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
    at org.scalatra.DynamicScope$class.withResponse(DynamicScope.scala:78)
    at org.bdgenomics.mango.cli.VizServlet.withResponse(VizReads.scala:206)
    at org.scalatra.DynamicScope$$anonfun$withRequestResponse$1.apply(DynamicScope.scala:58)
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
    at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:69)
    at org.bdgenomics.mango.cli.VizServlet.withRequest(VizReads.scala:206)
    at org.scalatra.DynamicScope$class.withRequestResponse(DynamicScope.scala:57)
    at org.bdgenomics.mango.cli.VizServlet.withRequestResponse(VizReads.scala:206)
    at org.scalatra.ScalatraBase$class.handle(ScalatraBase.scala:125)
    at org.bdgenomics.mango.cli.VizServlet.org$scalatra$servlet$ServletBase$$super$handle(VizReads.scala:206)
    at org.scalatra.servlet.ServletBase$class.handle(ServletBase.scala:53)
    at org.bdgenomics.mango.cli.VizServlet.handle(VizReads.scala:206)
    at org.scalatra.ScalatraServlet$class.service(ScalatraServlet.scala:60)
    at org.bdgenomics.mango.cli.VizServlet.service(VizReads.scala:206)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    at org.eclipse.jetty.server.Server.handle(Server.java:499)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
    at java.lang.Thread.run(Thread.java:745)

Spark 2.0 LazyMaterialization error after adding in proper locks at https://github.com/bigdatagenomics/mango/pull/235

**Comment by Georgehe4** [comment]
Resolve: Update empty RDD to use parallelize again.

**Comment by beckgael** [comment]
I've the same error, can you explain what do you mean by update empty RDD please

**Comment by Georgehe4** [comment]
@beckgael Instead of using the empty RDD function (which has been remove), such as `sc.emptyRDD[(T1, T2)]`, use `sc.parallelize[(T1,T2)](Array[(T1,T2)]())`
